version: "2.4"
services:
  app:
    image: samoilov/memoryleak-performance:latest
    environment:
      - JAVA_OPTS=-XX:+HeapDumpOnOutOfMemoryError -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9099 -Dcom.sun.management.jmxremote.rmi.port=9099 -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=192.168.0.116 -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000
      - BYTE_ARRAY_SIZE=500
      - LD_PRELOAD=/usr/local/lib/libjemalloc.so
      - MALLOC_CONF=prof_leak:true,prof_final:true
    ports:
      - "8080:8080"
      - "8000:8000"
      - "9099:9099"
      - "8849:8849"
    mem_limit: 100M
    volumes:
      - ./reports:/reports
      - ./out:/db
