version: "2.4"
services:
  app:
    image: samoilov/memoryleak:latest
    environment:
      - JAVA_OPTS=-Xmx40m -Xms30m -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9098 -Dcom.sun.management.jmxremote.rmi.port=9098 -Dcom.sun.management.jmxremote.local.only=false
      - BYTE_ARRAY_SIZE=500
    ports:
      - "8080:8080"
      - "9098:9098"
    mem_limit: 50M

